# Used when a commit is pushed to the repository
name: build-snapshot

on:
  push:
    branches:
      - main

env:
  MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
  MAVEN_SECRET: ${{ secrets.MAVEN_SECRET }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Build artifacts
        run: ./gradlew build publish
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Taufuscator
          path: build/libs
